apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-3
  name: nginx-3
spec:
  containers:
  - image: nginx:1.26.0
    name: nginx-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
